env:
  browser: true
  es2020: true
extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/recommended'
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 11
  sourceType: module
rules:
  @typescript-eslint/no-require-imports: warn
plugins:
  - '@typescript-eslint'
rules: {}
