name: Stacked PR Orchestrator
on: # PR
    pull_request:
      types: [closed]
jobs:
  orchestrate:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

